FROM centos:6

# Install Ansible (use pip to install Ansible v2)
RUN yum -y install epel-release
RUN yum -y install git sudo python-pip python-devel gcc initscripts
RUN yum clean all
RUN pip install paramiko PyYAML Jinja2 httplib2 six ansible argparse

# Disable requiretty
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Install Ansible inventory file
RUN mkdir /etc/ansible/
RUN echo -e '[local]\nlocalhost ansible_connection=local' > /etc/ansible/hosts

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/sbin/init"]
